services:
  mysql:
    image: mysql:8.0
    command: 
      - --max_allowed_packet=256M
      - --wait_timeout=28800
      - --interactive_timeout=28800
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: print3d
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10